"""users table

Revision ID: 11e4b93c1dd0
Revises: a83a0f63983d
Create Date: 2023-03-21 22:06:03.753522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e4b93c1dd0'
down_revision = 'a83a0f63983d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=13), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_phonenumber'), ['phonenumber'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phonenumber'))
        batch_op.drop_column('phonenumber')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
